name: Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: snehassneha4578-collab

      - name: Publish to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cd dist
          git init
          git checkout -b pacman-output
          git add .
          git commit -m "chore: update Pac-Man contribution graph"

          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/snehassneha4578-collab/snehassneha4578-collab.git"
          git push --force origin pacman-output

