name: Snake Contribution Graph

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: snehassneha4578-collab
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cd dist
          git init
          git checkout -b output
          git add .
          git commit -m "chore: update Snake contribution graph"

          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/snehassneha4578-collab/snehassneha4578-collab.git"
          git push --force origin output
